[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "DfAxVwzZccekFR6LZJWSb2t46wUGwGKheh39v3cYv3yZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/zonda/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
